import type {
  DistrictCard,
  Flashcard,
  GameState,
  GarageUpgrade,
  RouteDefinition,
  Skater,
} from "./types";

export const MAX_SQUAD_SIZE = 6;

export const ROUTES: RouteDefinition[] = [
  {
    id: "glass-loop",
    name: "Glass Loop",
    district: "Mirror Harbor",
    summary: "Fast clinic refills through polished alleys and mag-rail crossings.",
    durationMinutes: 12,
    batteryCost: 15,
    payoutCredits: 110,
    repGain: 4,
    riskTier: 1,
    cargo: ["meds", "documents"],
  },
  {
    id: "temple-drift",
    name: "Temple Drift",
    district: "Temple Strip",
    summary: "Fashion rush jobs with dense crowds, higher fares, and tighter turns.",
    durationMinutes: 18,
    batteryCost: 19,
    payoutCredits: 175,
    repGain: 6,
    riskTier: 2,
    cargo: ["fashion", "food", "nightlife"],
  },
  {
    id: "subgrid-shift",
    name: "Subgrid Shift",
    district: "Subgrid Ward",
    summary: "Undertunnel component drops where signal loss trades for fewer checkpoints.",
    durationMinutes: 24,
    batteryCost: 24,
    payoutCredits: 235,
    repGain: 7,
    riskTier: 2,
    cargo: ["parts", "smuggling", "repair kits"],
  },
  {
    id: "stormline-sprint",
    name: "Stormline Sprint",
    district: "Ion Heights",
    summary: "Prototype courier work high above the city with premium pay and brutal drain.",
    durationMinutes: 32,
    batteryCost: 30,
    payoutCredits: 340,
    repGain: 10,
    riskTier: 3,
    cargo: ["prototype", "premium", "black budget"],
  },
];

export const STARTER_SKATERS: Skater[] = [
  {
    id: "nyx",
    handle: "Nyx Vector",
    specialty: "Signal Ghost",
    boardName: "VX Phantom",
    accent: "#14f1ff",
    loadout: "Silent hub motors, EMP clip bag, raincloak shell",
    maxBattery: 100,
    battery: 100,
    speedMultiplier: 1.1,
    reputation: 12,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
  {
    id: "echo",
    handle: "Echo Jett",
    specialty: "Rail Drifter",
    boardName: "Aero Flicker",
    accent: "#ff4fd8",
    loadout: "Carbon deck, thermal courier case, signal jammer",
    maxBattery: 100,
    battery: 100,
    speedMultiplier: 1.02,
    reputation: 9,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
  {
    id: "kilo",
    handle: "Kilo Flux",
    specialty: "Grid Bruiser",
    boardName: "Torque Hound",
    accent: "#ffd447",
    loadout: "Torque booster, armored crate rig, illegal suspension kit",
    maxBattery: 120,
    battery: 120,
    speedMultiplier: 0.95,
    reputation: 15,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
  {
    id: "vex",
    handle: "Vex Hollow",
    specialty: "Static Smuggler",
    boardName: "Shade Nine",
    accent: "#9f6bff",
    loadout: "Noise scrambler, ghost tires, counterfeit courier seal",
    maxBattery: 95,
    battery: 95,
    speedMultiplier: 1.15,
    reputation: 11,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
  {
    id: "zen",
    handle: "Zen-9",
    specialty: "Corporate Defector",
    boardName: "Metro Sever",
    accent: "#7bf17d",
    loadout: "Forked dispatch AI, metro firmware exploit, cargo latch drones",
    maxBattery: 110,
    battery: 110,
    speedMultiplier: 1,
    reputation: 13,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
  {
    id: "maya",
    handle: "Maya Circuit",
    specialty: "Street Oracle",
    boardName: "Forecast X",
    accent: "#ff7a59",
    loadout: "Traffic predictor visor, pulse wheel kit, ad-beam scanner",
    maxBattery: 90,
    battery: 90,
    speedMultiplier: 1.2,
    reputation: 8,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  },
];

export const DISTRICT_CARDS: DistrictCard[] = [
  {
    zone: "Mirror Harbor",
    title: "Healthcare demand loop",
    description: "Steady low-risk jobs ideal for leveling fresh riders and stabilizing daily cashflow.",
    highlights: [
      "Short route length for frequent completions",
      "Low battery drain supports idle battery recovery",
      "Best first stop after a rewarded recharge",
    ],
  },
  {
    zone: "Temple Strip",
    title: "Tip-heavy nightlife corridor",
    description: "A mid-risk route family that works well for ad-driven comeback moments and board cosmetics.",
    highlights: [
      "Higher payout per minute than starter districts",
      "Natural place for event cards and surge bonuses",
      "Strong fit for monetized skip timers and cosmetics",
    ],
  },
  {
    zone: "Ion Heights",
    title: "Premium contract lane",
    description: "Late-game district that drains batteries hard and makes rewarded energy boosts feel meaningful.",
    highlights: [
      "Premium cargo creates aspirational progression",
      "Battery pressure makes recharge rewards valuable",
      "Good foundation for pass-tier or VIP contracts",
    ],
  },
];

export const GARAGE_UPGRADES: GarageUpgrade[] = [
  {
    id: "smart-charger",
    label: "Smart Charger",
    description: "Improves passive battery recovery while riders idle in the garage.",
    costCredits: 750,
    batteryBoost: 8,
  },
  {
    id: "route-cache",
    label: "Route Cache AI",
    description: "Surfaces the best payout route in the map view and increases dispatch efficiency.",
    costCredits: 1200,
    batteryBoost: 0,
  },
  {
    id: "deck-lab",
    label: "Deck Lab",
    description: "Unlocks premium board skins and higher-end garage tuning hooks.",
    costCredits: 1800,
    batteryBoost: 12,
  },
];

export const createInitialState = (): GameState => {
  const skaters = STARTER_SKATERS.slice(0, MAX_SQUAD_SIZE).map((skater) => ({
    ...skater,
    routeId: undefined,
    routeProgressMs: 0,
    totalRuns: 0,
    totalCreditsEarned: 0,
    lastUpdatedAt: new Date().toISOString(),
  }));

  const flashcards: Flashcard[] = skaters.map((skater) => ({
    id: skater.id,
    title: skater.handle,
    subtitle: skater.specialty,
    body: `${skater.handle} rides the ${skater.boardName}. Their loadout is tuned for high-speed automated delivery loops.`,
    accent: skater.accent,
  }));

  return {
    credits: 120,
    premiumFuelCells: 3,
    lastTickAt: new Date().toISOString(),
    monetization: {
      rewardedRechargeCount: 0,
      rewardedRepairCount: 0,
      admobStatus: "mock",
      pendingReward: null,
    },
    skaters,
    flashcards,
    routes: ROUTES.map((route) => ({ ...route, cargo: [...route.cargo] })),
    garageUpgrades: GARAGE_UPGRADES.map((upgrade) => ({ ...upgrade })),
    districtCards: DISTRICT_CARDS.map((card) => ({
      ...card,
      highlights: [...card.highlights],
    })),
    notifications: [
      "Neon dispatch online. Assign up to 6 skateboarders to autonomous delivery loops.",
      "Rewarded recharge currently uses a web mock and is ready to swap to Google AdMob on Android.",
    ],
  };
};
